-- Bookkeeping for the "someone opened the site" alert.
--
-- Both tables are written only by the `visit` Edge Function using the service
-- role, which bypasses RLS. They are covered by RLS with no policies at all, so
-- an anonymous or signed-in caller holding the anon key can neither read the
-- visit history nor forge an entry.

-- One row per address, holding the last time it was allowed to alert. This is
-- flood protection: without it, anyone who finds the site can hold down refresh
-- and bury a real alert under hundreds of fake ones.
create table visit_alerts (
  ip            text primary key,
  last_alert_at timestamptz not null default now(),
  suppressed    int not null default 0
);

-- One row per browser that has ever opened the site, so an alert can say
-- whether this device is new or one that has been here before. The id is
-- generated by the browser and kept in its local storage; clearing site data
-- makes a device look new again, which is the correct failure direction.
create table visit_devices (
  device_id     text primary key,
  first_seen_at timestamptz not null default now(),
  last_seen_at  timestamptz not null default now(),
  visits        int not null default 1,
  last_role     text
);

alter table visit_alerts  enable row level security;
alter table visit_devices enable row level security;
